import NeuralNetwork.NeuralNetwork;
import StockData.CCIStockData;
import StockData.CMOStockData;
import StockData.StockMovement;
import StockData.TRIXStockData;

import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static final String API_KEY = "GMGWOUIFSQ7HLN85";

    public static void main(String[] args) {
        NeuralNetwork network = new NeuralNetwork(2, 4);

    }
}
